"""initial schema - all 12 tables

Revision ID: aa636a85e171
Revises: 
Create Date: 2026-03-03 16:22:02.197235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa636a85e171'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_results', 'reopen_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analytics_results', 'avg_resolution_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analytics_results', 'defect_leakage_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('module_risk_scores', 'reopen_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('module_risk_scores', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.alter_column('module_risk_scores', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('module_risk_scores', 'reopen_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analytics_results', 'defect_leakage_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analytics_results', 'avg_resolution_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analytics_results', 'reopen_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
